### ISSUE TITLE
Style all of the web pages using CSS

### ISSUE THREAD

**Issue by rmpolanco** [zxin1007/Assignment-01#5]
This could be done using 1 stylesheet for all 3 pages, or 3 seperate stylesheets (1 for each). I think it'd be better to have just 1 stylesheet so all of the pages could have the same color/design/layout.

**Comment by abdoulguira** [comment]
It will be a good idea and will look more professional to have 1 css file for all the pages. I think making 3 css files will make the work difficult. what do you guys think?

**Comment by zxin1007** [comment]
agreed, let's have it in 1 css file
